In [5]:
# Import required libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [10]:
# Collect the training and test data
df1 = pd.read_csv("mongodb_dataset.csv")
print(df1.head(5))
df2 = pd.read_csv("mongodb_dataset_test.csv")
print(df2.head(5))

   log_level  tech_stack_status
0          9                  3
1          9                  3
2          9                  3
3          9                  3
4          9                  3
   log_level  tech_stack_status
0          9                  3
1          9                  3
2          9                  3
3          9                  3
4          9                  3


In [11]:
# Import required libraries to use Logistic Regression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix, accuracy_score

In [12]:
x_train = df.drop('tech_stack_status', axis=1)
y_train = df['tech_stack_status']
#x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)
logmodel = LogisticRegression(solver='lbfgs', multi_class='multinomial')
logmodel.fit(x_train, y_train)
print(logmodel.coef_)
print(logmodel.intercept_)
print(logmodel.n_iter_)

[[-2.44937981]
 [ 1.75655045]
 [ 0.69282936]]
[ 20.79464088 -18.91897078  -1.8756701 ]
[48]


In [13]:
x_test = df2.drop('tech_stack_status', axis=1)
y_test = df2['tech_stack_status']

predictions = logmodel.predict(x_test)
print(classification_report(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(accuracy_score(y_test, predictions))

              precision    recall  f1-score   support

           1       0.48      0.88      0.62        17
           2       0.95      0.67      0.78        57
           3       0.55      0.62      0.58        26

    accuracy                           0.69       100
   macro avg       0.66      0.72      0.66       100
weighted avg       0.77      0.69      0.70       100

[[15  2  0]
 [ 6 38 13]
 [10  0 16]]
0.69
